---
name: Eden
on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: [master]

jobs:
  integration:
    runs-on: ubuntu-20.04
    steps:
      - name: get eden
        uses: actions/checkout@v2
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - name: setup
        run: |
          sudo apt update
          sudo apt install -y qemu-utils qemu-system-x86
      - name: build eden
        run: |
          make build-tests
      - name: run
        run: |
          ./eden config add default
          ./eden config set default --key=eve.accel --value=false
          echo > tests/workflow/testdata/eden_stop.txt
          ./eden test ./tests/workflow -v debug
      - name: Collect logs
        if: ${{ always() }}
        run: |
          ./eden log --format json > trace.log
          ./eden info > info.log
      - name: Store raw test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: 'eden-report'
          path: |
              ${{ github.workspace }}/trace.log
              ${{ github.workspace }}/info.log
              ${{ github.workspace }}/dist/default-eve.log
