---
name: EdenGCP
on:  # yamllint disable-line rule:truthy
  push:
    branches: [master]
# yamllint disable rule:line-length
jobs:
  integration:
    runs-on: ubuntu-20.04
    steps:
      - name: get eden
        uses: actions/checkout@v2
      - name: Check
        run: |
          for addr in $(ip addr list|sed -En -e 's/.*inet ([0-9.]+).*/\1/p')
          do
              if echo "$addr" | grep -q -E "10.11.(12|13).[0-9]+"; then
                echo "$addr overlaps with test"; exit 1
              fi
              if echo "$addr" | grep -q -E "10.8.0.[0-9]+"; then
                echo "$addr overlaps with vpn"; exit 1
              fi
          done
      - name: Public IP
        id: ip
        run: |
          PUBLIC_IP=$(curl -s https://api.ipify.org/?format=text)
          if [[ ! $PUBLIC_IP =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then exit 1; fi
          echo "::set-output name=ipv4::$PUBLIC_IP"
      - name: setup packages
        run: |
          sudo apt update
          sudo apt install -y qemu-utils openvpn jq
      - name: try
        run: |
          make build
          ./eden config add default
          ./eden config set default --key=eve.accel --value=false
          ./eden setup
          ./eden start
          ./eden eve onboard
          ./eden controller edge-node get-config
          echo "$(./eden controller edge-node get-config)"
          echo "{"a":1}"
