---
name: Eden
on:
  pull_request:
    branches: [ master ]

jobs:
  integration:
    runs-on: ubuntu-20.04
    steps:
      - name: setup
        run: |
          sudo apt update
          sudo apt install -y qemu-utils qemu-system-x86
      - name: get eden
        uses: actions/checkout@v2
      - name: build eden
        run: |
          make clean
          make build-tests
      - name: run
        run: |
          ./eden config add default
          ./eden config set default --key=eve.accel --value=false
          echo > tests/workflow/testdata/eden_stop.txt
          ./eden test ./tests/workflow -v debug
      - name: Collect logs
        if: ${{ always() }}
        run: |
          ./eden log --format json |tee trace.log
          ./eden stop
      - name: Store raw test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: 'eden-report'
          path: ${{ github.workspace }}/trace.log
